#! /usr/bin/env perl

require '/home/cml/mime.pl';

#$debug=1;
$def_charset="utf-8";
$def_charsets="us-ascii:utf-8";

$_ .= $line while ($line=<>);
$msg = unmime(\$_, \$_, '', '', 'all, removeattach');
$debug && print "====== Unmime finished =====\n";
print $msg;
if (@attach) {
	print "==========\n";
	print "Attaches:\n";
	foreach $att (@attach) {
		print "- " . $att->{"filename"} . "\n";
	}
}
